# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'lbruenf'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu: 
  - name: Projetos
    submenu:
      - name: Hanseníase
        link: /projects/hansen
      - name: Toxoplasmose
        link: /projects/toxoplasma
      - name: Ensino a Distância
        link: /projects/ead
  - name: Blog
    link: /
  - name: Tags
    link: /tags
  - name: Sobre
    link: /about
  - name: Equipe
    link: /members
  # - name: Follow me
  #   submenu:
  #     - name: GitHub
  #       icon: github
  #       link: http://github.com/alainpham
  #     - name: LinkedIn
  #       icon: linkedin-square
  #       link: http://www.linkedin.com/in/alainpham
  #     - name: Twitter
  #       icon: twitter
  #       link: https://twitter.com/koint
    
